# Generated by Django 5.0.3 on 2024-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll_number', models.PositiveIntegerField()),
                ('contact_number', models.PositiveIntegerField()),
                ('room_number', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=30)),
                ('hostel_name', models.CharField(max_length=100)),
                ('subject_of_complaint', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('complaint_description', models.CharField(max_length=300)),
            ],
        ),
    ]
