# Generated by Django 5.0.3 on 2024-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
