# Generated by Django 5.0.3 on 2024-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_email_alter_complaint_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
