# Generated by Django 5.0.3 on 2024-03-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=100)),
                ('subject_of_complaint', models.CharField(max_length=100)),
                ('complaint', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
